[backend]
db_url = "postgres://postgres:postgr3s@localhost/hazel"
migrations = "/usr/share/hazel/migrations/"
storage = "/var/lib/hazel/storage/"

[web]
max_upload_filesize_mb = 10
resources = "/usr/share/hazel/resources/"

[server]
port = 8080

[auth]
superuser_password = "PleaseChangeThis"
